const assets = {
  source: new URL("../design/character-identity-prototype/character/assets/reference-dog/source.jpg", import.meta.url).href,
  sourceCard: new URL("../design/character-identity-prototype/character/assets/duoduo/card.jpg", import.meta.url).href,
  generatedSheet: new URL("../design/character-identity-prototype/character/assets/generated/duoduo-sheet/sheet-02.png", import.meta.url).href,
  fullFront: new URL("../design/character-identity-prototype/character/assets/generated/duoduo-zones/full_front.png", import.meta.url).href,
  fullSide: new URL("../design/character-identity-prototype/character/assets/generated/duoduo-zones/full_side.png", import.meta.url).href,
  fullBack: new URL("../design/character-identity-prototype/character/assets/generated/duoduo-zones/full_back.png", import.meta.url).href,
  halfBody: new URL("../design/character-identity-prototype/character/assets/generated/duoduo-zones/half_body.png", import.meta.url).href,
  faceFront: new URL("../design/character-identity-prototype/character/assets/generated/duoduo-zones/face_front.png", import.meta.url).href,
  faceLeft: new URL("../design/character-identity-prototype/character/assets/generated/duoduo-zones/face_left.png", import.meta.url).href,
  faceRight: new URL("../design/character-identity-prototype/character/assets/generated/duoduo-zones/face_right.png", import.meta.url).href,
  outfit: new URL("../design/character-identity-prototype/character/assets/generated/duoduo-zones/outfit.png", import.meta.url).href,
  shoes: new URL("../design/character-identity-prototype/character/assets/generated/duoduo-zones/shoes.png", import.meta.url).href,
  bag: new URL("../design/character-identity-prototype/character/assets/generated/duoduo-zones/bag.png", import.meta.url).href,
};

export const CHARACTER_ZONE_DEFS = [
  {
    id: "full_front",
    group: "body",
    label: "Full Front",
    role: "front standing body view",
    crop: [5, 5, 378, 405],
    aspect: "3 / 4",
    image: assets.fullFront,
    improvement: "Improve the front standing body view while preserving the same tiny white toy-breed dog, compact body, short legs, round puffy face, dark eyes, cream-white coat, and calm posture.",
  },
  {
    id: "full_side",
    group: "body",
    label: "Full Side",
    role: "left side body view",
    crop: [385, 5, 785, 405],
    aspect: "3 / 4",
    image: assets.fullSide,
    improvement: "Improve the side profile so it reads as the same dog from the front view: tiny body, short legs, fluffy cream-white coat, soft ears, and no breed drift.",
  },
  {
    id: "full_back",
    group: "body",
    label: "Full Back",
    role: "back body view",
    crop: [793, 5, 1102, 405],
    aspect: "3 / 4",
    image: assets.fullBack,
    improvement: "Improve the back view anatomy and coat continuity without changing scale, breed, background, or the identity cues visible in the other body views.",
  },
  {
    id: "half_body",
    group: "body",
    label: "Half Body",
    role: "front three-quarter half-body portrait",
    crop: [1110, 5, 1531, 405],
    aspect: "3 / 4",
    image: assets.halfBody,
    improvement: "Improve the half-body portrait for face readability and body consistency while keeping the same calm tiny white dog and studio lighting.",
  },
  {
    id: "face_front",
    group: "face",
    label: "Face Front",
    role: "front face close-up",
    crop: [5, 412, 531, 758],
    aspect: "1 / 1",
    image: assets.faceFront,
    improvement: "Improve the front face close-up. Lock the round puffy baby face, oversized glossy dark eyes set close together, small black button nose, compact muzzle, and cream-white wispy coat.",
  },
  {
    id: "face_left",
    group: "face",
    label: "Face Left",
    role: "left face profile close-up",
    crop: [538, 412, 1014, 758],
    aspect: "1 / 1",
    image: assets.faceLeft,
    improvement: "Improve the left face profile while matching the front face identity: short compact muzzle, soft floppy ears, dark round eye, and no poodle-like snout drift.",
  },
  {
    id: "face_right",
    group: "face",
    label: "Face Right",
    role: "right face profile close-up",
    crop: [1021, 412, 1531, 758],
    aspect: "1 / 1",
    image: assets.faceRight,
    improvement: "Improve the right face profile while matching the front and left face zones. Preserve muzzle length, puffy head shape, ear softness, and coat texture.",
  },
  {
    id: "outfit",
    group: "detail",
    label: "Coat Detail",
    role: "coat texture detail zone",
    crop: [5, 765, 531, 1018],
    aspect: "1 / 1",
    image: assets.outfit,
    improvement: "Improve the coat texture detail only. Keep it cream-white, fluffy, slightly wispy, natural, and consistent with the same dog instead of a perfect show-groomed coat.",
  },
  {
    id: "shoes",
    group: "detail",
    label: "Paws",
    role: "front paws detail zone",
    crop: [538, 765, 1014, 1018],
    aspect: "1 / 1",
    image: assets.shoes,
    improvement: "Improve the paws detail only. Repair anatomy, paw count, fur shape, and scale while preserving the same tiny toy-breed dog.",
  },
  {
    id: "bag",
    group: "detail",
    label: "Toy Prop",
    role: "blue plush toy prop detail zone",
    crop: [1021, 765, 1531, 1018],
    aspect: "1 / 1",
    image: assets.bag,
    improvement: "Improve the blue plush toy prop detail while keeping it separate from the dog identity zones and avoiding text, logos, or watermark-like marks.",
  },
];

export const CHARACTER_DESIGN = {
  id: "duoduo-reference-dog",
  code: "ID-G01",
  name: "Reference Dog Multi-View",
  shortName: "Duoduo",
  tagline: "Imagegen sheet split by VLM into reusable identity zones.",
  source: assets.source,
  sourceCard: assets.sourceCard,
  generatedSheet: assets.generatedSheet,
  sourcePackagePath: "design/character-identity-prototype/",
  spec: [
    ["Age", "Toy-breed puppy / young dog"],
    ["Identity", "Small white toy-breed reference dog"],
    ["Build", "Tiny lap-sized body, short legs, compact stance"],
    ["Face", "Round puffy face, dark glossy eyes, small black nose"],
    ["Coat", "Cream-white dense curly coat with wispy flyaway hair"],
    ["Expression", "Calm, direct, slightly curious"],
    ["Lighting", "Soft gray studio lighting"],
    ["Background", "Plain light gray studio background"],
  ],
  identityContract: [
    "Preserve the same small white toy-breed dog from the source image.",
    "Keep the round puffy face, dark eyes, black nose, cream-white curly coat, tiny body, and calm expression.",
    "Do not change the dog into another breed, a taller poodle-like dog, or a show-groomed round-head bichon.",
  ],
  negativePrompt: "No text, labels, logos, watermark, extra legs, malformed paws, distorted face, different breed, different coat color, or cartoon style.",
  sheetPrompt:
    "Generate a clean photorealistic 10-panel multi-view contact sheet of the same tiny white toy-breed puppy from the reference. Preserve lap-sized body, close-set glossy dark eyes, tiny black button nose, compact muzzle, cream-white fluffy coat, soft floppy ears, slightly uneven puppy grooming, small paws, calm curious expression, red/pink harness or chest strap in body views, and the blue plush toy prop. Plain light gray studio background. No text, labels, logos, or watermark.",
  zones: CHARACTER_ZONE_DEFS,
};
